config/routes.rb
Rails.application.routes.draw do
  resources :sales_staffs
  resources :bills
  resources :bill_tos
  resources :companies
  devise_for :users
  resources :members do
    member do
      get 'bill'
      post 'pdf'
    end
  end
  root to: 'members#index'
end

app/models/bill_to.rb
class BillTo < ApplicationRecord
  has_many :members
  has_many :sales_staffs
end

app/controllers/bill_tos_controller.rb
class BillTosController < ApplicationController
  before_action :set_bill_to, only: [:show, :edit, :update, :destroy]

  # GET /bill_tos
  # GET /bill_tos.json
  def index
    @q = BillTo.ransack(params[:q])
    @bill_tos = @q.result(distinct: true).page(params[:page]).per(50)
  end

  # GET /bill_tos/1
  # GET /bill_tos/1.json
  def show
  end

  # GET /bill_tos/new
  def new
    @bill_to = BillTo.new
  end

  # GET /bill_tos/1/edit
  def edit
  end

  # POST /bill_tos
  # POST /bill_tos.json
  def create
    @bill_to = BillTo.new(bill_to_params)

    respond_to do |format|
      if @bill_to.save
        format.html { redirect_to @bill_to, notice: '追加しました' }
        format.json { render :show, status: :created, location: @bill_to }
      else
        format.html { render :new }
        format.json { render json: @bill_to.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bill_tos/1
  # PATCH/PUT /bill_tos/1.json
  def update
    respond_to do |format|
      if @bill_to.update(bill_to_params)
        format.html { redirect_to @bill_to, notice: '更新しました' }
        format.json { render :show, status: :ok, location: @bill_to }
      else
        format.html { render :edit }
        format.json { render json: @bill_to.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bill_tos/1
  # DELETE /bill_tos/1.json
  def destroy
    @bill_to.destroy
    respond_to do |format|
      format.html { redirect_to bill_tos_url, notice: '削除しました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill_to
      @bill_to = BillTo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_to_params
      params.fetch(:bill_to, {})
      params.require(:bill_to).permit(
        :name,
        :phone_num_1,
        :email_1,
      )
    end
end

app/helpers/bill_tos_helper.rb
module BillTosHelper
end

app/views/bill_tos/_form.html.erb
<%= form_with(model: bill_to, local: true) do |form| %>
  <% if bill_to.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bill_to.errors.count, "error") %> prohibited this bill_to from being saved:</h2>

      <ul>
      <% bill_to.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bill_tos/edit.html.erb
<h1>Editing Bill To</h1>

<%= render 'form', bill_to: @bill_to %>

<%= link_to 'Show', @bill_to %> |
<%= link_to 'Back', bill_tos_path %>

app/views/bill_tos/index.html.erb
<p id="notice"><%= notice %></p>

<p class="lead"> 請求先一覧</p>

<%= search_form_for @q do |f| %>
  <div class="input-group mb-3">
    <span class="input-group-text" id="">名　前</span>
    <%= f.search_field :name_cont, { class: 'form-control' } %>
  </div>
  <%= f.submit '検索', { class: "btn btn-primary active" } %>
<% end %>


<table class="table" style="margin-top:20px;">
  <thead>
    <tr>
      <th></th>
      <th>請求先</th>
      <th>電話番号</th>
      <th>メール</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>


    <% @bill_tos.each do |bill_to| %>
      <tr>
        <td><%= check_box_tag 'bill_to_ids[]', bill_to.id, true, {} %></td>
        <td><%= bill_to.name %></td>
        <td><%= bill_to.phone_num_1 %></td>
        <td><%= bill_to.email_1 %></td>
        <td><%= link_to '編集', edit_bill_to_path(bill_to), { class: "btn btn-link" } %></td>
        <td><%= link_to '削除', bill_to, method: :delete, data: { confirm: '削除してもよろしいですか？' },class: "btn btn-link" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '請求先追加', new_bill_to_path, { class: "btn btn-primary active" } %>

app/views/bill_tos/new.html.erb
<h1>請求先追加</h1>

<%= render 'form', bill_to: @bill_to %>

<%= link_to 'Back', bill_tos_path %>

app/views/bill_tos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bill_to.name %>
</p>

<%= link_to 'Edit', edit_bill_to_path(@bill_to) %> |
<%= link_to 'Back', bill_tos_path %>