config/routes.rb
Rails.application.routes.draw do
  resources :sales_staffs
  resources :bills
  resources :bill_tos
  resources :companies
  devise_for :users
  resources :members do
    member do
      get 'bill'
      post 'pdf'
    end
  end
  root to: 'members#index'
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :bill_to
  belongs_to :company
  belongs_to :sales_staff
  paginates_per 50
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy, :bill]

  def index
    @q = Member.ransack(params[:q])
    @members = @q.result.page(params[:page])
    @bill_tos = BillTo.all
  end

  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: '追加しました' }
      else
        format.html { render :new }
      end
    end
  end

  def bill
    @bill = Bill.new
    @bill.bill_to_name = @member.bill_to.name
    @bill.company_name = @member.company.name
    @bill.member_name = @member.name
  end

  def pdf
    render 'bills/create'
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      params.require(:member).permit(:name)
      if @member.update(member_params)
        format.html { redirect_to @member, notice: '更新しました' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: '削除しました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.fetch(:member, {})
      params.require(:member).permit(
        :name,
        :member_no,
        :birthday,
        :sex,
        :company_id,
        :bill_to_id,
        :sales_staff_id,
        :payment_terms,
        :unit_price,
        :upper_standerd,
        :lower_standerd,
        :dev_content,
        :task
      )
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_with(model: member, local: true) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>
      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <ul class="list-group" style="width: 50%;">
    <li class="list-group-item">
      所属会社: <%= form.collection_select(:bill_to_id, Company.all, :id, :name, include_blank: '選択してください') %>
    </li>
    <li class="list-group-item">
      社員番号: <%= form.text_field :member_no %>
    </li>
    <li class="list-group-item">
      名前: <%= form.text_field :name %>
    </li>
    <li class="list-group-item">
      誕生日: <%= form.text_field :birthday %>
    </li>
    <li class="list-group-item">
      性別: <%= form.text_field :sex %>
    </li>
    <li class="list-group-item">
      請求先: <%= form.text_field :bill_to_id %>
    </li>
    <li class="list-group-item">
      営業担当: <%= form.text_field :sales_staff_id %>
    </li>
    <li class="list-group-item">
      支払いサイト: <%= form.text_field :payment_terms %>
    </li>
    <li class="list-group-item">
      単価: <%= form.text_field :unit_price %>
    </li>
    <li class="list-group-item">
      上限時間: <%= form.text_field :upper_standerd %>
    </li>
    <li class="list-group-item">
      下限時間: <%= form.text_field :lower_standerd %>
    </li>
    <li class="list-group-item">
      開発内容: <%= form.text_field :dev_content %>
    </li>
  </ul>


  <div class="actions" style="margin-top:10px;">
    <%= form.submit '追加' , { class:"btn btn-primary" } %>
  </div>
<% end %>

app/views/members/bill.html.erb
<%= form_with model: @bill, method: :post do |form| %>
  <% if @bill.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @bill.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= hidden_field :create, :type, { value: 'create_pdf' } %>
  <ul class="list-group input-group" style="width: 100%;">
    <li class="list-group-item">
      会社: <%= @member.company.name %>
    </li>
    <li class="list-group-item">
      請求先: <%= @member.bill_to.name %>
    </li>
    <li class="list-group-item">
      稼働者: <%= @member.name %>
    </li>
    <li class="list-group-item">
      稼働月: <%= select_month(form) %>
    </li>
    <li class="list-group-item">
      件名: <%= @member.dev_content %>
    </li>
    <li class="list-group-item">
      業務名: <%= @member.task %>
    </li>
    <li class="list-group-item input-group mb3">
      作業期間: <%= last_month_beginning_date(form) %> 〜 <%= last_month_end_date(form) %>
    </li>
    <li class="list-group-item input-group mb3">
      人月: <%= form.number_field :term, step: "0.01", value: 1 %>
    </li>
    <li class="list-group-item input-group mb3">
      単価: <%= number_to_currency(@member.unit_price, :unit => "￥", :precision => 0) %>円
    </li>
    <li class="list-group-item input-group mb3">
      作業時間: <%= form.number_field :term, step: "0.01" %>
    </li>
    <li class="list-group-item input-group mb3">
      超過（基準時間　<%= @member.upper_standerd %>）
       時間単価: <%= @member.upper_standerd %>
       時間単価: <%= @member.upper_standerd %>
    </li>
    <li class="list-group-item input-group mb3">
      控除（基準時間　<%= @member.lower_standerd %>）
      <%= form.hidden_field :lower_standerd, value: @member.lower_standerd %>
    </li>
    <li class="list-group-item input-group mb3">
      残業 / 控除 <%= form.text_field :bill_to_name, readonly: true %>
    </li>
    <li class="list-group-item input-group mb3">
      小計 <%= form.text_field :total, readonly: true %>
    </li>
    <li class="list-group-item input-group mb3">
      税額 <%= form.text_field :total, readonly: true %>
    </li>
    <li class="list-group-item input-group mb3">
      費用請求 <%= form.text_field :total, readonly: false %>
    </li>
    <li class="list-group-item input-group mb3">
      合計 <%= form.text_field :total, readonly: true %>
      <%= link_to '計算', 'javascript:void(0);', { onclick: "cal()", class: "btn btn-primary active" } %>
    </li>
  </ul>

  <div class="actions">
    <%= form.submit('請求書作成') %>
  </div>
<% end %>

app/views/members/bill.pdf.erb
dddddddddddd

app/views/members/edit.html.erb
<h1 style="margin-bottom:36px;">社員編集</h1>

<%= render 'form', member: @member %>


<div style="margin:40px 0;">
 <%= link_to '追加情報', @member %> |
 <%= link_to '戻る', members_path %>
</div>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<p class="lead">社員一覧</p>

<%= search_form_for @q do |f| %>
  <div class="input-group mb-3">
    <span class="input-group-text" id="">名　前</span>
    <%= f.search_field :name_cont, { class: 'form-control' } %>
  </div>
  <div class="input-group mb-3">
    <%= f.label '請求先', { class: 'input-group-text' } %>
    <%= f.collection_select(:bill_to_id_eq, @bill_tos, :id, :name, include_blank: '選択してください') %>
  </div>
  <%= f.submit '検索', { class: "btn btn-primary active" } %>
  <%= link_to '社員追加', new_member_path, { class: "btn btn-primary active" } %>
<% end %>
<div style="height: 250px; overflow: auto;">
  <table class="table" style="margin-bottom: 0;">
    <thead>
      <tr>
        <th>氏名</th>
        <th>請求先</th>
        <th>単価(円)</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
    <div class="pagination" style="height:56px; margin-top: 20px;">
    <%= paginate @members %>
    </div>

      <% @members.each do |member| %>
        <tr>
          <td><%= link_to member.name, member %></td>
          <td><%= member.bill_to.name %></td>
          <td><%= member.unit_price&.to_s(:delimited) %></td>
          <td><%= link_to '編集', edit_member_path(member) %></td>
          <td><%= link_to '請求書作成', bill_member_path(member) %></td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
    </tfoot>
  </table>
</div>

<div class="pagination" style="margin:5px 5px 10px;">
  <%= paginate @members %>
</div>

app/views/members/new.html.erb
<h1 style="margin-bottom:36px;">社員追加</h1>

 <%= render 'form', member: @member %>

<div style="margin:40px 0;">
 <%= link_to '戻る', members_path %>
</div>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<h1 style="margin-bottom: 36px;">社員情報</h1>

<ul class="list-group" style="width: 50%;">
  <li class="list-group-item">社員番号: <%= @member.member_no %></li>
  <li class="list-group-item">名前: <%= @member.name %></li>
  <li class="list-group-item">誕生日: <%= @member.birthday %></li>
  <li class="list-group-item">性別: <%= @member.sex %></li>
  <li class="list-group-item">請求先: <%= @member.bill_to.name %></li>
  <li class="list-group-item">営業担当: <%= @member.sales_staff.name %></li>
  <li class="list-group-item">支払いサイト: <%= @member.payment_terms %></li>
  <li class="list-group-item">単価: <%= @member.unit_price&.to_s(:delimited) %>円</li>
  <li class="list-group-item">上限時間: <%= @member.upper_standerd %></li>
  <li class="list-group-item">下限時間: <%= @member.lower_standerd %></li>
  <li class="list-group-item">開発内容: <%= @member.dev_content %></li>
</ul>

<div style="margin: 40px 0;">
<%= link_to '編集', edit_member_path(@member) %> |
<%= link_to '戻る', members_path %>
</div>